[tool.poetry]
name = "modern-tdd-python"
version = "0.1.0"
description = ""
authors = ["Chaipat Suwannapoom <bchaipats@gmail.com>"]
readme = "README.md"
packages = [{include = "modern_tdd_python"}]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2.2"
flask-pydantic = "^0.11.0"
pre-commit = "^2.20.0"
mypy = "^0.991"
black = "^22.12.0"
isort = "^5.11.4"
flake8 = "^6.0.0"
darglint = "^1.8.1"
requests = "^2.28.1"
sphinx = "^5.3.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
